<!-- Navigation principal -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-white bg-white fixed-top">
    <div class="container-fluid">
      <?php $logo = Html::img("logo.png"); ?>  
      <?= Html::link("index", $logo, "title='ALBERTO PRIMAVERA - Broker Seguros'") ?> 
        <!--<a class="navbar-brand" href="index.html">Secretaría de Cultura y Extensión Universitaria <small>U.T.N-F.R.G.P</small></a>-->
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
           <li class="nav-item dropdown">
               <a class="nav-link" href="https://www.albertoprimavera.com.ar" target="_blank"><i class="fab fa-chrome"></i>
              WEB
            </a>
            
          </li>
          <li class="nav-item dropdown">
              <a class="nav-link" href="https://www.facebook.com/segurosalbertoprimavera" target="_blank"><i class="fab fa-facebook"></i>
              FACEBOOK
            </a>
          </li>
          <li class="nav-item dropdown">
              <a class="nav-link" href="https://www.instagram.com/albertoprimaveraseguros" target="_blank"><i class="fab fa-instagram"></i>
              INSTAGRAM
            </a>
          </li>
          <li class="nav-item dropdown">
              <a class="nav-link" href="https://api.whatsapp.com/send?phone=5491123313661&text=Por favor, solicito la siguiente información: "  target="_blank"><i class="fab fa-whatsapp"></i>
              +54(011)2331-3661
              </a>
          </li>
          <li class="nav-item dropdown">
              <a class="nav-link" href="tel:+5491147938493" target="_blank"><i class="fas fa-phone"></i>
              +54(011) 4793-8493 / 9828
              </a>
          </li>
          <li class="nav-item dropdown">
              <a class="nav-link" href="mailto:seguros@albertoprimavera.com.ar" target="_blank"><i class="fas fa-envelope"></i>
              seguros@albertoprimavera.com.ar
              </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>


