<!-- Page Content -->
<?php $text = "INFO: ".$Campania->asunto; ?> <!-- TEXTO PARA WHATSAPP -->  
  <div class="container">
      
      <a href="https://wa.me/5491162232067?text=<?=$text?>" class="float" target="_blank" class="flotante" target="_blank">
      <i class="fab fa-whatsapp"></i>
    </a>
      

    <!-- Page Heading/Breadcrumbs -->
    <h1 class="mt-4 mb-3"><?= $titulo ?>
    </h1>

    

    <div class="row">
        

      <!-- Blog Entries Column -->
      <div class="col-lg-8 mb-4">
        <h3>Envianos tu consulta</h3>
        <?= Form::open("comunicacion/campaniaProcesar") ?>
        <?= Form::hidden("campania_id", "", $Campania->id) ?>  
        
          <div class="control-group form-group">
            <div class="controls">
              <label>Nombre/s y Apellido/s:</label>
              <?= Form::text("nombre", "class ='form-control' title='Por favor complete con su nombre y apellido' placeholder='NOMBRE/S y APELLIDO/S' required") ?>
              <!--<input type="text" class="form-control" id="name" required data-validation-required-message="Please enter your name.">-->
              <p class="help-block"></p>
            </div>
          </div>
          <div class="control-group form-group">
            <div class="controls">
              <label>Email:</label>
              <?= Form::email("email", "class='form-control' title='Por favor complete con su email' placeholder='EMAIL' required='required'") ?>
            </div>
          </div>
          <div class="control-group form-group">
            <div class="controls">
              <label>Celular:</label>
              <?= Form::text("celular", "class='form-control' title='Por favor complete con su celular' placeholder='CELULAR'") ?>
            </div>
          </div>
          <div class="control-group form-group">
            <div class="controls">
              <label>Consulta:</label>
              <?= Form::textarea("consulta", "class='form-control' title='Por favor, complete con su consulta' placeholder='CONSULTA:' cols='100' rows='10' required='required'") ?>
            </div>
          </div>
          <div id="success"></div>
          <!-- For success/fail messages -->
          <?= Form::submit("ENVIAR CONSULTA", "class='btn btn-primary'") ?>
          
        <?= Form::close() ?>
      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-lg-4 mb-4">
        <h3>ODONTIT S.A.</h3>
        <p>
            <i class="fas fa-map-marker"></i> Azcuénaga 1077 4°D. C.A.B.A.<br>
          <i class="fas fa-phone"></i> (011) 4825-0221 Líneas Rotativas<br>
          <i class="fas fa-envelope"></i> info@odontit.com<br>
          <i class="fab fa-whatsapp"></i> +54 (011) 6223-2067<br>
          <i class="fas fa-clock"></i> Lun. a Vie. de 10 a 18hs.<br>
          <i class="fas fa-ban"></i> Sábados y Domingos CERRADO.
        </p>
        <hr>
        <p>
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3284.3371082250947!2d-58.40196058445704!3d-34.595636180461675!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x95bcca96d16cca3d%3A0xe418d6abe93edca!2sOdontit%20Sa!5e0!3m2!1ses-419!2sar!4v1590152931566!5m2!1ses-419!2sar" width="350" height="350" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
        </p>
      </div>
      
    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->
  
  <?php
    function mesCastellano ($fecha) {
        $fecha = substr($fecha, 0, 10);
        //$numeroDia = date('d', strtotime($fecha));
        //$dia = date('l', strtotime($fecha));
        $mes = date('F', strtotime($fecha));
        //$anio = date('Y', strtotime($fecha));
        $meses_ES = array("Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre");
        $meses_EN = array("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December");
        $nombreMes = str_replace($meses_EN, $meses_ES, $mes);
        $nombreMes = strtoupper($nombreMes);
        return $nombreMesTresCaracteres = substr($nombreMes, 0, 3);
      }
  ?>