<!-- SLIDERS -->
<header>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <!-- Slide One - Set the background image for this slide in the line below -->
        <div class="carousel-item active" style="background-image: url('http://web.extension-utn-frgp.com.ar/img/slide1.jpg')">
          <div class="carousel-caption d-none d-md-block">
            <h3>Aprovechá el tiempo, te brindamos los CURSOS ONLINE</h3>
            <p><?= Html::link("cursos/listarCursos", "<i class='fas fa-book-open'></i> VER CURSOS", "class='btn btn-primary'") ?></p>
          </div>
        </div>
        <!-- Slide Two - Set the background image for this slide in the line below -->
        <div class="carousel-item" style="background-image: url('http://web.extension-utn-frgp.com.ar/img/slide2.jpg')">
          <div class="carousel-caption d-none d-md-block">
            <h3>SERVICIOS TECNOLÓGICOS</h3>
             <p><?= Html::link("#", "<i class='fas fa-vial'></i> ir a LABTEC", "class='btn btn-primary'") ?></p>
          </div>
        </div>
        <!-- Slide Three - Set the background image for this slide in the line below -->
        <div class="carousel-item" style="background-image: url('http://web.extension-utn-frgp.com.ar/img/slide3.jpg')">
          <div class="carousel-caption d-none d-md-block text-dark">
            <h3>Cultura, talleres y eventos</h3>
            <p><?= Html::link("#", "<i class='fas fa-theater-masks'></i> Más info sobre CULTURA", "class='btn btn-primary'") ?></p>
          </div>
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Proximo</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Anterior</span>
      </a>
    </div>
  </header>

  <!-- Page Content -->
  <div class="container">

      <h1 class="my-4"><marquee scrollamount="15" >Como es de publico conocimiento y siguiendo la cuarentena establecida por el gobierno, solamente estamos atendiendo al publico via mail en : capacitacion@red.frgp.utn.edu.ar </marquee></h1>
    <!-- Marketing Icons Section -->
    
    
    

  </div>
