<!-- SLIDERS -->
<header>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <!-- Slide One - Set the background image for this slide in the line below -->
        <div class="carousel-item active" style="background-image: url('https://landing.albertoprimavera.com.ar/img/slide1.jpg')">
          <div class="carousel-caption d-none d-md-block">
            <!--<h3>ODONTIT IMPLANT SYSTEMS</h3>-->
            <p><a class="btn btn-dark" href="https://www.albertoprimavera.com.ar"><i class='fab fa-chrome'></i> ir a la WEB</a></p>
          </div>
        </div>
        <!-- Slide Two - Set the background image for this slide in the line below -->
        
        <!-- Slide Three - Set the background image for this slide in the line below -->
        
      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Proximo</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Anterior</span>
      </a>
    </div>
  </header>

  <!-- Page Content -->
  <div class="container">

      <h1 class="my-4 text-dark"><marquee scrollamount="15" >Ahora contáctenos por WhatsApp: +54 (011) 2331-3661 </marquee></h1>
    <!-- Marketing Icons Section -->
    
    
    

  </div>
