<!DOCTYPE html>
<html lang="es">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Sistema de GESTIÓN para H-D Bs. As.">
  <meta name="author" content="JAVIER SALA - jasal@itmedia.com.ar">

  <title>HARLEY-DAVIDSON Bs. As. GESTIÓN - Crear nueva cuenta</title>

  <!-- Custom fonts for this template-->
  
  <?php Tag::css('vendor/fontawesome-free/css/all.min') ?>   
  <!-- <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css"> -->    
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <?php Tag::css('sb-admin-2.min') ?>   
  <!-- <link href="css/sb-admin-2.min.css" rel="stylesheet"> -->
  
  
  <?= Html::includeCss() ?> <!-- IMPRIME ESTILOS -->

</head>

<body class="bg-gray-900"> <!-- bg-gradient-primary antes estaba asi -->

  <div class="container">

    <?= View::content() ?>

  </div>

  <!-- Bootstrap core JavaScript-->
  <?= Tag::js('vendor/jquery/jquery.min.js') ?>
  <!-- <script src="vendor/jquery/jquery.min.js"></script> -->
  <?= Tag::js('vendor/bootstrap/js/bootstrap.bundle.min.js') ?>
  <!-- <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script> -->

  <!-- Core plugin JavaScript-->
  <?= Tag::js('vendor/jquery-easing/jquery.easing.min.js') ?>
  <!-- <script src="vendor/jquery-easing/jquery.easing.min.js"></script> -->

  <!-- Custom scripts for all pages-->
  <?= Tag::js('js/sb-admin-2.min.js') ?>
  <!-- <script src="js/sb-admin-2.min.js"></script> -->

</body>

</html>
