<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>HDG - Harley-Davidson Bs. As. Gestión</title>

  <!-- Custom fonts for this template-->
  <?php Tag::css('vendor/fontawesome-free/css/all.min') ?>   
  <!-- <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css"> -->
  
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <?php Tag::css('sb-admin-2.min') ?>   
  <!-- <link href="css/sb-admin-2.min.css" rel="stylesheet"> -->
  
  <!-- ESTILO PARA datatables para los LISTADOS -->
  <?php Tag::css('vendor/datatables/dataTables.bootstrap4.min') ?>   
  <!-- <link href="vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet"> -->
  
   <!-- ESTILO PARA el AUTOCOMPLETE -->
  <?php Tag::css('autocompletevanilla/auto-complete') ?>   
  <!-- <link href="autocompletevanilla/auto-complete.css" rel="stylesheet"> -->
  
  <?= Html::includeCss() ?> <!-- IMPRIME ESTILOS -->
  
  <!-- para autocompletar los input text -->
  <?php echo Tag::js('autocompletevanilla/auto-complete') ?>
  <!-- <script src="autocompletevanilla/autocomplete.js"></script> -->
   <?php echo Tag::js('autocompletevanilla/auto-complete.min') ?>
  <!-- <script src="autocompletevanilla/auto-complete.min.js"></script> -->
  
</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <?= View::partial("admin/sidebar") ?>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <?= View::partial("admin/topbar") ?>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">
            
            <?= View::content() ?>
         
        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <?= View::partial("admin/footer") ?>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="login.html">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <?php echo Tag::js('vendor/jquery/jquery.min') ?>
  <!-- <script src="vendor/jquery/jquery.min.js"></script> -->
  
  <?php echo Tag::js('vendor/bootstrap/js/bootstrap.bundle.min') ?>
  <!-- <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script> -->

  <!-- Core plugin JavaScript-->
  <?php echo Tag::js('vendor/jquery-easing/jquery.easing.min') ?>
  <!-- <script src="vendor/jquery-easing/jquery.easing.min.js"></script> -->

  <!-- Custom scripts for all pages-->
  <?php echo Tag::js('js/sb-admin-2.min') ?>
  <!-- <script src="js/sb-admin-2.min.js"></script> -->

  <!-- Page level plugins -->
  <?php echo Tag::js('vendor/chart.js/Chart.min') ?>
  <!--<script src="vendor/chart.js/Chart.min.js"></script> -->
  <?php echo Tag::js('vendor/datatables/jquery.dataTables.min') ?>
  <!-- <script src="vendor/datatables/jquery.dataTables.min.js"></script> -->
  <?php echo Tag::js('vendor/datatables/dataTables.bootstrap4.min') ?>
  <!--<script src="vendor/datatables/dataTables.bootstrap4.min.js"></script> -->
  
  <!-- Page level custom scripts -->
  <?php echo Tag::js('js/demo/chart-area-demo') ?>
  <!-- <script src="js/demo/chart-area-demo.js"></script> -->
  <?php echo Tag::js('js/demo/chart-pie-demo') ?>
  <!-- <script src="js/demo/chart-pie-demo.js"></script> -->
  <?php echo Tag::js('js/demo/datatables-demo') ?>
  <!-- <script src="js/demo/datatables-demo.js"></script> -->

</body>

</html>
