<ul class="navbar-nav bg-gray-900 sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon">
          <?= Html::img("bsicon.png", "HDG") ?>  
          <!-- <i class="fas fa-laugh-wink"></i> -->
        </div>
          <div class="sidebar-brand-text mx-3">H-D. Ges <sup>0.1</sup></div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item active">
        <?= Html::link("index", "<i class='fas fa-fw fa-tachometer-alt'></i><span>Panel</span>", "class='nav-link'") ?>  
        <!--
        <a class="nav-link" href="index.html">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
          -->
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <!--
      <div class="sidebar-heading">
        Ventas
      </div>
      -->

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseImagenes" aria-expanded="true" aria-controls="collapseImagenes">
          <i class="fas fa-fw fa-images"></i>
          <span>Imágenes</span>
        </a>
        <div id="collapseImagenes" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Imágenes</h6>
            <?= Html::link("imagenes/eventos", "<i class='fas fa-fw fa-edit'></i> <span>EVENTOS</span>", "class='collapse-item'") ?>
            <?= Html::link("partes/listarPartes", "<i class='fas fa-fw fa-list-ol'></i> <span>Listar PARTES</span>", "class='collapse-item'") ?>
          </div>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseVentas" aria-expanded="true" aria-controls="collapseVentas">
          <i class="fas fa-fw fa-shopping-cart"></i>
          <span>Ventas</span>
        </a>
        <div id="collapseVentas" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Ventas potenciales</h6>
            <?= Html::link("ventaPotencial/crear", "<i class='fas fa-fw fa-edit'></i> <span>Crear</span>", "class='collapse-item'") ?>
            <?= Html::link("ventaPotencial/listar", "<i class='fas fa-fw fa-list'></i> <span>Listar</span>", "class='collapse-item'") ?>
          </div>
        </div>
      </li>
      
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePartes" aria-expanded="true" aria-controls="collapsePartes">
          <i class="fas fa-fw fa-puzzle-piece"></i>
          <span>Partes</span>
        </a>
        <div id="collapsePartes" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Repuestos / Accesorios</h6>
            <?= Html::link("partes/crearPartes", "<i class='fas fa-fw fa-edit'></i> <span>Crear PARTES</span>", "class='collapse-item'") ?>
            <?= Html::link("partes/listarPartes", "<i class='fas fa-fw fa-list-ol'></i> <span>Listar PARTES</span>", "class='collapse-item'") ?>
            <?= Html::link("partes/crearPedido", "<i class='fas fa-fw fa-edit'></i> <span>Crear Pedido</span>", "class='collapse-item'") ?>
            <?= Html::link("partes/listarPedidos", "<i class='fas fa-fw fa-list'></i> <span>Listar Pedidos</span>", "class='collapse-item'") ?>
          </div>
        </div>
      </li>
      

      <!-- Nav Item - Utilities Collapse Menu -->
      <!--
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
          <i class="fas fa-fw fa-wrench"></i>
          <span>Utilities</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Custom Utilities:</h6>
            <a class="collapse-item" href="utilities-color.html">Colors</a>
            <a class="collapse-item" href="utilities-border.html">Borders</a>
            <a class="collapse-item" href="utilities-animation.html">Animations</a>
            <a class="collapse-item" href="utilities-other.html">Other</a>
          </div>
        </div>
      </li>
      -->

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Addons
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <!--
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
          <i class="fas fa-fw fa-folder"></i>
          <span>Pages</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Login Screens:</h6>
            <a class="collapse-item" href="login.html">Login</a>
            <a class="collapse-item" href="register.html">Register</a>
            <a class="collapse-item" href="forgot-password.html">Forgot Password</a>
            <div class="collapse-divider"></div>
            <h6 class="collapse-header">Other Pages:</h6>
            <a class="collapse-item" href="404.html">404 Page</a>
            <a class="collapse-item" href="blank.html">Blank Page</a>
          </div>
        </div>
      </li>
      -->

      <!-- Nav Item - Charts -->
      <!--
      <li class="nav-item">
        <a class="nav-link" href="charts.html">
          <i class="fas fa-fw fa-chart-area"></i>
          <span>Charts</span></a>
      </li>
      -->

      <!-- Nav Item - Tables -->
      <!--
      <li class="nav-item">
        <a class="nav-link" href="tables.html">
          <i class="fas fa-fw fa-table"></i>
          <span>Tables</span></a>
      </li>
      -->

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>   